version: '3'

services:
  db:
    restart: always
    image: postgres:13.6
    container_name: event_service_container
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - event_service_data:/var/lib/postgresql/data

  zookeeper:
      image: confluentinc/cp-zookeeper
      ports:
          - 2181:2181
      environment:
          ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  event_service_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

