spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    password: '1234'
    driver-class-name: org.hibernate.dialect.MySQL5Dialect
    username: root
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useSSL=false&createDatabaseIfNotExist=true
database:
  name: auth_db
  host: localhost
  port: '3306'
server:
  error:
    whitelabel:
      enabled: 'false'
  port: '8081'
